sudo: require
services:
    - docker
language: generic 

before_install:
    - docker build -t ccifuentes95/react-frontend -f Dockerfile.dev .

script:
    - docker run -e CI=true ccifuentes95/react-frontend npm test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "react-frontend"
    env: "ReactFrontend-env"
    bucket_name: "elasticbeanstalk-us-east-2-572736066318"
    bucket_path: "ReactFrontend"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY